#creating the docker image based on the nginx webserver
FROM nginx:1.10.1-alpine                     
#Copying files from host machine into the Docker image.
COPY index.html /usr/share/nginx/html  
#container will listen on the 8080 network port at runtime. 
EXPOSE 8080
#run when the container starts, running the webserver and globally defined that the nginx will run on background
CMD ["nginx", "-g", "daemon off;"]