
# version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://server:5000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
    profiles:
      - server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    depends_on:
      server:
        condition: service_healthy
    profiles:
      - client

# sudo docker compose --profile server --profile client up
# sudo docker compose --profile server up