FROM python:3.11-slim

WORKDIR /app

COPY server.py .

# RUN pip install Flask \
#     && apt-get update \
#     && apt-get install -y wget \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*
RUN pip install Flask \
    && apt-get update \
    && apt-get install -y curl

EXPOSE 5000

CMD ["python", "server.py"]
