
version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://server:5000/health || exit 1"]
      # test: ["CMD-SHELL", "wget --spider --quiet http://localhost:5000/health || exit 1"]
      # test: ["CMD-SHELL", "echo 'Server is up'"]
      interval: 30s
      timeout: 15s
      retries: 5
    networks:
      - webnet

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    depends_on:
      server:
       condition: service_healthy
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
