#using the latest version of ubuntu image from docker hub
FROM ubuntu:latest
#getting the updated packages, install the listed packages without any recommended additional packages. Installed the packages required compliers etc for the software building, c++ libareries, python3 and git etc
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    python3 \
    git
WORKDIR /workspace
COPY . /workspace
CMD ["bash"]